AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
